# Generated by Django 5.0.6 on 2026-01-29 05:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('DEPOSIT_PENDING', 'New Deposit Pending'), ('WITHDRAWAL_PENDING', 'New Withdrawal Pending'), ('USER_VERIFICATION', 'User Verification Needed'), ('SYSTEM_ALERT', 'System Alert')], max_length=50)),
                ('message', models.TextField()),
                ('related_id', models.IntegerField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.TextField()),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='AdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('DEPOSIT_APPROVE', 'Deposit Approved'), ('DEPOSIT_CANCEL', 'Deposit Cancelled'), ('WITHDRAWAL_APPROVE', 'Withdrawal Approved'), ('WITHDRAWAL_CANCEL', 'Withdrawal Cancelled'), ('USER_EDIT', 'User Edited'), ('PLAN_EDIT', 'Plan Edited'), ('INVESTMENT_CANCEL', 'Investment Cancelled')], max_length=50)),
                ('description', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
