# Generated by Django 5.0.6 on 2026-01-29 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailyprofit',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='dailyprofit',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='investment',
            name='capital_returned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='investment',
            name='profit_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
